// Slider definitions and visual presets shared by the interface.
export const controls = [
  {
    id: 'height',
    label: '水滴高度',
    min: 0,
    max: 240,
    value: 80,
    unit: '%',
    uniform: 'uHeight',
    factor: 0.01,
    section: 'lens',
  },
  {
    id: 'distance',
    label: '背景距离',
    min: 0,
    max: 400,
    value: 8,
    unit: '%',
    uniform: 'uDistance',
    factor: 0.01,
    section: 'lens',
  },
  {
    id: 'ior',
    label: '折射率',
    min: 1,
    max: 1.8,
    step: 0.001,
    value: 1.333,
    uniform: 'uIor',
    section: 'lens',
    digits: 3,
  },
  {
    id: 'roundness',
    label: '圆润度',
    min: 0,
    max: 100,
    value: 85,
    unit: '%',
    uniform: 'uRoundness',
    factor: 0.01,
    section: 'lens',
  },
  {
    id: 'specular',
    label: '高光强度',
    min: 0,
    max: 150,
    value: 65,
    unit: '%',
    uniform: 'uSpecular',
    factor: 0.01,
    section: 'light',
  },
  {
    id: 'shadow',
    label: '内阴影',
    min: 0,
    max: 100,
    value: 45,
    unit: '%',
    uniform: 'uShadow',
    factor: 0.01,
    section: 'light',
  },
  {
    id: 'dispersion',
    label: '边缘色散',
    min: 0,
    max: 100,
    value: 20,
    unit: '%',
    uniform: 'uDispersion',
    factor: 0.01,
    section: 'light',
  },
];

export const presets = {
  soft: {
    height: 80,
    distance: 8,
    ior: 1.333,
    roundness: 85,
    specular: 65,
    shadow: 45,
    dispersion: 20,
  },
  glass: {
    height: 155,
    distance: 17,
    ior: 1.5,
    roundness: 38,
    specular: 85,
    shadow: 60,
    dispersion: 35,
  },
  inverted: {
    height: 115,
    distance: 68,
    ior: 1.333,
    roundness: 95,
    specular: 65,
    shadow: 48,
    dispersion: 8,
  },
};
